networks:
  modelpolisher:

volumes:
  pgadmin-data:

configs:
  pgadmin-server-config:
    file: ./pgadmin-servers.json

services:

  biggdb:
    image: schmirgel/bigg_db:1.6
    container_name: modelpolisher_pgadmin_biggdb
    networks:
      - modelpolisher

  adb:
    image: schmirgel/annotatedb:0.1.1
    container_name: modelpolisher_pgadmin_adb
    networks:
      - modelpolisher

  pgadmin:
    image: dpage/pgadmin4
    container_name: modelpolisher_pgadmin
    depends_on:
      - biggdb
      - adb
    environment:
      DEFAULT_SERVER_PORT: 80
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    configs:
      - source: pgadmin-server-config
        target: /pgadmin4/servers.json
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - modelpolisher
