//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.04.27 at 01:32:33 PM CEST
//
package edu.ucsd.sbrg.miriam.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for format complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="format">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="elements" type="{http://www.biomodels.net/MIRIAM/}elements"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "format", propOrder = {"elements"})
public class Format {

  @XmlElement(required = true)
  protected Elements elements;
  @XmlAttribute(name = "name", required = true)
  protected String name;


  /**
   * Gets the value of the elements property.
   * 
   * @return
   *         possible object is
   *         {@link Elements }
   */
  public Elements getElements() {
    return elements;
  }


  /**
   * Sets the value of the elements property.
   * 
   * @param value
   *        allowed object is
   *        {@link Elements }
   */
  public void setElements(Elements value) {
    this.elements = value;
  }


  /**
   * Gets the value of the name property.
   * 
   * @return
   *         possible object is
   *         {@link String }
   */
  public String getName() {
    return name;
  }


  /**
   * Sets the value of the name property.
   * 
   * @param value
   *        allowed object is
   *        {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }
}
