//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.04.27 at 01:32:33 PM CEST
//
package edu.ucsd.sbrg.miriam.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for resource complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataResource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataEntityExample" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataEntry" type="{http://www.biomodels.net/MIRIAM/}dataEntry"/>
 *         &lt;element name="dataInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataInstitution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.biomodels.net/MIRIAM/}resourceID" />
 *       &lt;attribute name="obsolete" type="{http://www.biomodels.net/MIRIAM/}TrueOrFalse" />
 *       &lt;attribute name="primary" type="{http://www.biomodels.net/MIRIAM/}TrueOrFalse" />
 *       &lt;attribute name="preferred" type="{http://www.biomodels.net/MIRIAM/}TrueOrFalse" />
 *       &lt;attribute name="state" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reliability" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resource", propOrder = {"dataResource", "dataEntityExample", "dataEntry", "dataInfo",
  "dataInstitution", "dataLocation"})
public class Resource {

  @XmlElement(required = true)
  protected String dataResource;
  protected String dataEntityExample;
  @XmlElement(required = true)
  protected String dataEntry;
  @XmlElement(required = true)
  protected String dataInfo;
  @XmlElement(required = true)
  protected String dataInstitution;
  @XmlElement(required = true)
  protected String dataLocation;
  @XmlAttribute(name = "id", required = true)
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String id;
  @XmlAttribute(name = "obsolete")
  protected Boolean obsolete;
  @XmlAttribute(name = "primary")
  protected Boolean primary;
  @XmlAttribute(name = "preferred")
  protected Boolean preferred;
  @XmlAttribute(name = "state")
  protected String state;
  @XmlAttribute(name = "reliability")
  protected Byte reliability;


  /**
   * Gets the value of the dataResource property.
   * 
   * @return
   *         possible object is
   *         {@link String }
   */
  public String getDataResource() {
    return dataResource;
  }


  /**
   * Sets the value of the dataResource property.
   * 
   * @param value
   *        allowed object is
   *        {@link String }
   */
  public void setDataResource(String value) {
    this.dataResource = value;
  }


  /**
   * Gets the value of the dataEntityExample property.
   * 
   * @return
   *         possible object is
   *         {@link String }
   */
  public String getDataEntityExample() {
    return dataEntityExample;
  }


  /**
   * Sets the value of the dataEntityExample property.
   * 
   * @param value
   *        allowed object is
   *        {@link String }
   */
  public void setDataEntityExample(String value) {
    this.dataEntityExample = value;
  }


  /**
   * Gets the value of the dataEntry property.
   * 
   * @return
   *         possible object is
   *         {@link String }
   */
  public String getDataEntry() {
    return dataEntry;
  }


  /**
   * Sets the value of the dataEntry property.
   * 
   * @param value
   *        allowed object is
   *        {@link String }
   */
  public void setDataEntry(String value) {
    this.dataEntry = value;
  }


  /**
   * Gets the value of the dataInfo property.
   * 
   * @return
   *         possible object is
   *         {@link String }
   */
  public String getDataInfo() {
    return dataInfo;
  }


  /**
   * Sets the value of the dataInfo property.
   * 
   * @param value
   *        allowed object is
   *        {@link String }
   */
  public void setDataInfo(String value) {
    this.dataInfo = value;
  }


  /**
   * Gets the value of the dataInstitution property.
   * 
   * @return
   *         possible object is
   *         {@link String }
   */
  public String getDataInstitution() {
    return dataInstitution;
  }


  /**
   * Sets the value of the dataInstitution property.
   * 
   * @param value
   *        allowed object is
   *        {@link String }
   */
  public void setDataInstitution(String value) {
    this.dataInstitution = value;
  }


  /**
   * Gets the value of the dataLocation property.
   * 
   * @return
   *         possible object is
   *         {@link String }
   */
  public String getDataLocation() {
    return dataLocation;
  }


  /**
   * Sets the value of the dataLocation property.
   * 
   * @param value
   *        allowed object is
   *        {@link String }
   */
  public void setDataLocation(String value) {
    this.dataLocation = value;
  }


  /**
   * Gets the value of the id property.
   * 
   * @return
   *         possible object is
   *         {@link String }
   */
  public String getId() {
    return id;
  }


  /**
   * Sets the value of the id property.
   * 
   * @param value
   *        allowed object is
   *        {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }


  /**
   * Gets the value of the obsolete property.
   * 
   * @return
   *         possible object is
   *         {@link Boolean }
   */
  public Boolean isObsolete() {
    return obsolete;
  }


  /**
   * Sets the value of the obsolete property.
   * 
   * @param value
   *        allowed object is
   *        {@link Boolean }
   */
  public void setObsolete(Boolean value) {
    this.obsolete = value;
  }


  /**
   * Gets the value of the primary property.
   * 
   * @return
   *         possible object is
   *         {@link Boolean }
   */
  public Boolean isPrimary() {
    return primary;
  }


  /**
   * Sets the value of the primary property.
   * 
   * @param value
   *        allowed object is
   *        {@link Boolean }
   */
  public void setPrimary(Boolean value) {
    this.primary = value;
  }


  /**
   * Gets the value of the preferred property.
   * 
   * @return
   *         possible object is
   *         {@link Boolean }
   */
  public Boolean isPreferred() {
    return preferred;
  }


  /**
   * Sets the value of the preferred property.
   * 
   * @param value
   *        allowed object is
   *        {@link Boolean }
   */
  public void setPreferred(Boolean value) {
    this.preferred = value;
  }


  /**
   * Gets the value of the state property.
   * 
   * @return
   *         possible object is
   *         {@link String }
   */
  public String getState() {
    return state;
  }


  /**
   * Sets the value of the state property.
   * 
   * @param value
   *        allowed object is
   *        {@link String }
   */
  public void setState(String value) {
    this.state = value;
  }


  /**
   * Gets the value of the reliability property.
   * 
   * @return
   *         possible object is
   *         {@link Byte }
   */
  public Byte getReliability() {
    return reliability;
  }


  /**
   * Sets the value of the reliability property.
   * 
   * @param value
   *        allowed object is
   *        {@link Byte }
   */
  public void setReliability(Byte value) {
    this.reliability = value;
  }
}
